//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_UAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pasien()
        {
            this.Transaksis = new HashSet<Transaksi>();
        }
    
        public string kode_pasien { get; set; }
        public string nama_pasien { get; set; }
        public string alamat { get; set; }
        public string tempat_lahir { get; set; }
        public Nullable<System.DateTime> tanggal_lahir { get; set; }
        public string jenis_kelamin { get; set; }
        public string agama { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaksi> Transaksis { get; set; }
    }
}
