//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_UAS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaksi
    {
        public string kode_transaksi { get; set; }
        public Nullable<System.DateTime> tanggal { get; set; }
        public string kode_pasien { get; set; }
        public string kode_obat { get; set; }
        public string kode_dokter { get; set; }
        public Nullable<int> total { get; set; }
    
        public virtual Dokter Dokter { get; set; }
        public virtual Obat Obat { get; set; }
        public virtual Pasien Pasien { get; set; }
    }
}
